GET http://localhost:8000/clientes

###

GET http://localhost:8000/mascotas

###

GET http://localhost:8000/clienteId

###

GET http://localhost:8000/test

###

POST http://localhost:8000/clientes
Content-Type: application/json

{
    "nombre": "felipe",
    "apellido": "angarita",
    "telefono":"3185657114",
    "email": "jfaa@gmail.com",
    "password":"123"
}

###

PUT http://localhost:8000/clientes
Content-Type: application/json

{
    "idCliente":"2",
    "nombre": "j",
    "apellido": "angarita",
    "telefono":"3185657114",
    "email": "jfaa@gmail.com",
    "password":"123"
}

###

DELETE http://localhost:8000/clientes
Content-Type: application/json

{
  "idCliente": "2"
}

###

POST http://localhost:8000/mascotas
Content-Type: application/json

{
    "nombre": "Julian Jr",
    "raza": "Huski",
    "peso":"40kg",
    "idCliente": "1"
}

###

PUT http://localhost:8000/mascotas
Content-Type: application/json

{
    "idMascota":"3",
    "nombre": "Julian Jr",
    "raza": "Huski",
    "peso":"40kg",
    "idCliente": "3"
}

###

DELETE http://localhost:8000/mascotas